/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package write_people_strict_task2;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
